# Generated by Django 3.1.5 on 2021-04-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('places', 'distnace')},
        ),
    ]
