# Generated by Django 3.1.5 on 2021-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_auto_20210423_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='user',
            name='places',
            field=models.CharField(choices=[('1', 'eriyad'), ('2', 'kdr'), ('3', 'thrissur'), ('4', 'pppp'), ('5', 'kkkkkkk'), ('6', 'lllll'), ('7', 'bbbb'), ('8', 'kkkk')], default='1', max_length=20),
        ),
    ]
