# Generated by Django 3.1.5 on 2021-04-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_auto_20210423_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='USER',
        ),
    ]
