# Generated by Django 3.1.5 on 2021-04-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_auto_20210424_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrePaid',
            new_name='Place',
        ),
    ]
