# Generated by Django 3.1.5 on 2021-04-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_auto_20210424_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='distance',
            field=models.IntegerField(),
        ),
    ]
